apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jitsi
  serviceName: "jitsi-meet"
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: jicofo
          image: reg-dhc.app.corpintra.net/jitsi/jicofo:latest
          imagePullPolicy: Always
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: America/Los_Angeles
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
        - name: prosody
          image: reg-dhc.app.corpintra.net/jitsi/prosody:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sleep 30 && prosodyctl --config /config/prosody.cfg.lua register \"$JITSI_LOGIN_USER\" meet.jitsi \"$JITSI_LOGIN_PASSWORD\""]
          ports:
          - name: 5222-tcp
            containerPort: 5222
          - name: 5269-tcp
            containerPort: 5269
          - name: 5280-tcp
            containerPort: 5280
          - name: 5347-tcp
            containerPort: 5347
          env:
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JICOFO_COMPONENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_COMPONENT_SECRET
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: TZ
              value: America/Los_Angeles
            - name: ENABLE_AUTH
              value: "1"
            - name: ENABLE_GUESTS
              value: "1"
            - name: AUTH_TYPE
              value: "internal"
            - name: JITSI_LOGIN_USER
              valueFrom:
                secretKeyRef:
                  name: jitsi-credentials
                  key: username
            - name: JITSI_LOGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-credentials
                  key: password
        - name: web
          image: reg-dhc.app.corpintra.net/jitsi/web:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: JICOFO_AUTH_USER
              value: focus
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_GUEST_DOMAIN
              value: guest.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: XMPP_BOSH_URL_BASE
              value: http://127.0.0.1:5280
            - name: XMPP_MUC_DOMAIN
              value: muc.meet.jitsi
            - name: TZ
              value: America/Los_Angeles
            - name: DISABLE_HTTPS
              value: "0"
          volumeMounts:
          - name: icon-vol
            mountPath: /usr/share/jitsi-meet/images/watermark.png
            subPath: watermark.png
        - name: jvb
          image: reg-dhc.app.corpintra.net/jitsi/jvb:latest
          imagePullPolicy: Always
          ports:
          - name: 4443-tcp
            containerPort: 4443
          - name: 10000-udp
            containerPort: 10000
            protocol: UDP
          env:
            - name: XMPP_SERVER
              value: localhost
            - name: DOCKER_HOST_ADDRESS
              value: 127.0.0.1
            - name: XMPP_DOMAIN
              value: meet.jitsi
            - name: XMPP_AUTH_DOMAIN
              value: auth.meet.jitsi
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal-muc.meet.jitsi
            - name: JVB_STUN_SERVERS
              value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
            - name: JICOFO_AUTH_USER
              value: focus
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "false"
            - name: JVB_AUTH_USER
              value: jvb
            - name: JVB_PORT
              value: "30007"
            - name: JVB_TCP_PORT
              value: "30008"
            - name: JVB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JVB_AUTH_PASSWORD
            - name: JICOFO_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JICOFO_AUTH_PASSWORD
            - name: JVB_BREWERY_MUC
              value: jvbbrewery
            - name: TZ
              value: America/Los_Angeles
            - name: NAT_HARVESTER_LOCAL_ADDRESS
              value: 10.254.251.54
            - name: NAT_HARVESTER_PUBLIC_ADDRESS
              value: 141.113.50.16
            - name: TCP_HARVESTER_SSLTCP
              value: "false"
      volumes:
      - name: icon-vol
        configMap:
          name: jitsi-icon
      securityContext:
        runAsUser: 1001
      #   runAsGroup: 9999
      #   fsGroup: 9999
      #   supplementalGroups:
      #   - 9999
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  # - name: "https"
  #   port: 4443
  #   targetPort: 4443
  selector:
    k8s-app: jitsi
    #---
    #apiVersion: networking.k8s.io/v1beta1
    #kind: Ingress
    #metadata:
    #  name: jitsi
    #  namespace: jitsi
    #  annotations:
    #    kubernetes.io/ingress.class: traefik-prod
    #spec:
    #  rules:
    #  - host: ccs2sfmc.corpinter.net
    #    http:
    #      paths:
    #      - path: /
    #        backend:
    #          serviceName: web
    #          servicePort: http
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: jitsi-np
  namespace: jitsi
spec:
  podSelector:
    matchLabels:
      k8s-app: jitsi
  ingress:
    - ports:
      - port: 8080
        protocol: TCP
      - port: 4443
        protocol: TCP
      - port: 10000
        protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 10000
    protocol: UDP
    targetPort: 10000
    nodePort: 30007
  selector:
    k8s-app: jitsi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-tcp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 4443
    protocol: TCP
    targetPort: 4443
    nodePort: 30008
  selector:
    k8s-app: jitsi
